stages:
    - test

live+fullsystem:
    stage: test
    tags:
        - LinuxHighMemory
    allow_failure: false
    when: manual
    image:
        name: registry.opensuse.org/devel/openqa/containers/openqa-single-instance:latest
        entrypoint: ["/bin/bash", "-c"]
    before_script:
        # Bootstrap OpenQA Environment
        - .gitlab/scripts/openqa_bootstrap_nonsystemd_patch.sh
        # Wait openQA ready
        - ./utils/wait_openqa_ready.sh
        # Install dependencies
        - zypper --non-interactive install perl-Inline-Python python3-requests python3-beautifulsoup4
        # Download the latest image
        - python3 utils/download_image.py --latest
    script:
        - .gitlab/scripts/openqa_test.sh
    after_script:
        - .gitlab/scripts/collect_results.sh
    artifacts:
        paths:
            - testresults/