# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2026 Thomas Duckworth <tduck@filotimoproject.org>

[project]
name = "os-autoinst-distri-kdelinux"
version = "0.1.0"
description = "End-to-end tests for KDE Linux using openQA."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "colorlog>=6.12.0",
    "requests>=2.34.2",
    "fabric>=3.2.3",
    "ruff>=0.16.3",
]

# This is transformed into requirements.txt on the SUT,
# which is then installed with pip
[dependency-groups]
sut = [
    "unittest-xml-reporting>=4.0.0",
]

[tool.uv]
default-groups = []
