#!/usr/bin/env bash

set -euo pipefail

# hacks around constraints of selenium-webdriver-at-spi-run

export QT_ACCESSIBILITY=1
export QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1

if [[ "$1" =~ ^[0-9]+$ ]]; then
  # $1 is an existing PID, use it directly
  PID="$1"
else
  # $1 is a command, launch it
  "$1" &
  PID=$!
fi

source /tests/venv/bin/activate
KWIN_PID="$(pgrep -n kwin_wayland)" selenium-webdriver-at-spi-run python3 "$2" "$PID"
