# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2026 Thomas Duckworth <tduck@filotimoproject.org>
services:
  openqa:
    image: registry.opensuse.org/devel/openqa/containers/openqa-single-instance
    hostname: openqa
    container_name: openqa-single-instance
    ports:
      - "1443:443"
      - "1080:80"
    devices:
      - /dev/kvm
    working_dir: /casedir
    environment:
      - OPENQA_HOST_ADDR=localhost
      - OPENQA_SCHEME=http
      - OPENQA_SSH_USER=root
    volumes:
      - ..:/casedir
    entrypoint: ["/casedir/mocks/start-single-instance.sh"]

volumes:
  openqa-pgsql:
