# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2026 Thomas Duckworth <tduck@filotimoproject.org>
# SPDX-FileCopyrightText: 2026 Bhushan Shah <bhushan.shah@machinesoul.in>

import shutil
import tempfile
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path

from lib.worker.test_manifest import Manifest, Test, TestKind

_SYSEXT_TEST_ROOT = Path("usr/lib/kde-linux-openqa/tests")


@dataclass(frozen=True)
class StagedCaseDir:
    path: Path


def stage_sut_tests(
    sysext_root: Path,
    manifest: Manifest,
) -> None:
    """
    Package all the SUT tests and ship them in the sysext.
    """

    # Clear out any SUT test contents from an earlier sysext build.
    destination_root = sysext_root / _SYSEXT_TEST_ROOT
    shutil.rmtree(destination_root, ignore_errors=True)

    # Copy in all the SUT tests.
    for test in manifest.all_tests():
        if test.kind is TestKind.OPENQA:
            continue
        destination = destination_root / test.path
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(manifest.manifest_path.parent / test.path, destination)


def _render_wrapper(test: Test) -> str:
    """
    Automatically generate wrappers for SUT tests on the openQA side.
    """
    imports = ["from lib.test import cli_test"]
    if test.user:
        imports.append("from lib.common import user_manager")

    lines = [
        # REUSE-IgnoreStart
        "# Generated by lib.worker.test_layout; do not edit.",
        "# SPDX-License-Identifier: CC0-1.0",
        # REUSE-IgnoreEnd
        "from testapi import *",
        *imports,
        "",
    ]

    flags = {}
    if test.fatal:
        flags["fatal"] = 1
    if test.always_run:
        flags["always_run"] = 1
    if flags:
        lines.extend(
            [
                "",
                "def test_flags(self):",
                f"    return {flags!r}",
                "",
            ]
        )

    arguments = [repr(test.name)]
    if test.artifacts:
        arguments.append(f"artifacts={list(test.artifacts)!r}")

    arguments.append(f"timeout={test.timeout}")

    lines.extend(
        [
            "",
            "def run(self):",
            f"    test = cli_test.CliTest({', '.join(arguments)})",
        ]
    )

    run_arguments = [repr(test.path.as_posix())]
    if test.user:
        run_arguments.append(f"user=user_manager.{test.user}()")
    lines.append(f"    test.run_{test.kind.value}({', '.join(run_arguments)})")
    lines.append("")
    return "\n".join(lines)


def _render_main(tests: list[Test]) -> str:
    """Generate the CASEDIR scheduler and Python import bootstrap."""
    lines = [
        # REUSE-IgnoreStart
        "# Generated by lib.worker.test_layout; do not edit.",
        "# SPDX-License-Identifier: CC0-1.0",
        # REUSE-IgnoreEnd
        "use strict;",
        "use warnings;",
        "",
        "use Inline::Python qw(py_eval);",
        "use Cwd 'abs_path';",
        "use File::Basename;",
        "use lib dirname(abs_path(__FILE__)) . '/lib';",
        "",
        "my $casedir = dirname(abs_path(__FILE__));",
        r"$casedir =~ s/\\/\\\\/g;",
        r"$casedir =~ s/'/\\'/g;",
        'py_eval("import sys; sys.path.insert(0, \'$casedir\')");',
        "",
        "use testapi;",
        "use autotest;",
        "",
    ]
    lines.extend(
        f"autotest::loadtest({test.source.as_posix()!r});" for test in tests
    )
    lines.extend(["", "1;", ""])
    return "\n".join(lines)


@contextmanager  # allows using this in a with block
def staged_casedir(
    casedir: Path,
    suite: str,
    manifest: Manifest,
) -> Iterator[StagedCaseDir]:
    """
    Transiently generate a CASEDIR with a schedule in main.pm.
    """
    tests = list(manifest.suite(suite).enabled_tests)
    definitions: dict[Path, Test] = {}

    # Check that tests aren't defined multiple times ambiguously.
    for test in tests:
        if test.path in definitions and definitions[test.path] != test:
            raise ValueError(
                f"Conflicting definitions of {test.path} in suite {suite!r}"
            )
        definitions[test.path] = test

    # Create and build the transient casedir.
    with tempfile.TemporaryDirectory(prefix="kde-linux-openqa-casedir-") as tmp:
        destination = Path(tmp) / "casedir"
        destination.mkdir()
        (destination / "main.pm").write_text(_render_main(tests))
        for directory in ("lib", "needles"):
            shutil.copytree(casedir / directory, destination / directory)
        Path(tmp).chmod(0o755)

        # Generate openQA wrappers that call SUT tests and put them in our new
        # transient casedir.
        for test in tests:
            wrapper = destination / test.source
            wrapper.parent.mkdir(parents=True, exist_ok=True)
            if test.override:
                shutil.copy2(manifest.manifest_path.parent / test.override, wrapper)
            elif test.kind is TestKind.OPENQA:
                shutil.copy2(manifest.manifest_path.parent / test.path, wrapper)
            else:
                wrapper.write_text(_render_wrapper(test))

        yield StagedCaseDir(path=destination)
